/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionTableData: typeof import('./../../views/components/listings-table/action-table-data.vue')['default']
    Alert: typeof import('./../../views/components/alert.vue')['default']
    Banner: typeof import('./../../views/components/banner.vue')['default']
    BaseButton: typeof import('./../../views/components/base-button.vue')['default']
    BaseModal: typeof import('./../../views/components/base-modal.vue')['default']
    DropdownItem: typeof import('./../../views/components/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./../../views/components/DropdownMenu.vue')['default']
    EmptyTableRow: typeof import('./../../views/components/listings-table/empty-table-row.vue')['default']
    GithubLogo: typeof import('./../../views/components/github-logo.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    ItemImage: typeof import('./../../views/components/item-image.vue')['default']
    ItemSearch: typeof import('./../../views/components/item-search.vue')['default']
    ItemSelect: typeof import('./../../views/components/item-select.vue')['default']
    ItemTableData: typeof import('./../../views/components/listings-table/item-table-data.vue')['default']
    LayoutAccount: typeof import('@/views/layouts/account/layout-account.vue')['default']
    LayoutAdmin: typeof import('@/views/layouts/admin/layout-admin.vue')['default']
    LayoutMain: typeof import('@/views/layouts/main/layout-main.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    ListingForm: typeof import('./../../views/components/listing-form.vue')['default']
    ListingOffer: typeof import('./../../views/components/listing-offer.vue')['default']
    ListingOfferItem: typeof import('./../../views/components/listing-offer-item.vue')['default']
    ListingTable: typeof import('./../../views/components/listings-table/listing-table.vue')['default']
    ListingTableRow: typeof import('./../../views/components/listings-table/listing-table-row.vue')['default']
    NoteTableData: typeof import('./../../views/components/listings-table/note-table-data.vue')['default']
    Pagination: typeof import('./../../views/components/pagination.vue')['default']
    PopoverItem: typeof import('./../../views/components/PopoverItem.vue')['default']
    PopoverMenu: typeof import('./../../views/components/PopoverMenu.vue')['default']
    PriceTableData: typeof import('./../../views/components/listings-table/price-table-data.vue')['default']
    SnapSlider: typeof import('./../../views/components/snap-slider.vue')['default']
    SortHeader: typeof import('./../../views/components/sort-header.vue')['default']
    TimestampTableData: typeof import('./../../views/components/listings-table/timestamp-table-data.vue')['default']
    UsernamesAlert: typeof import('./../../views/components/usernames-alert.vue')['default']
    UsernameTableData: typeof import('./../../views/components/listings-table/username-table-data.vue')['default']
  }
}
